export { buildContinuityContext } from './context'
export { analyzeManuscript, createContinuityEngine } from './engine'
export {
  aliasConflictRule,
  builtinContinuityRules,
  locationRegistrationRule,
  loreRuleHitRule,
  povRegistrationRule,
  timelineReverseRule,
  unknownEntityRule,
} from './rules'
export type {
  AliasNamespace,
  AliasTarget,
  ContinuityContext,
  ContinuityDocument,
  ContinuityEngine,
  ContinuityEngineConfig,
  ContinuityIssue,
  ContinuityIssueCode,
  ContinuityReport,
  ContinuityRule,
  ContinuityStats,
  EntityKind,
  FactPattern,
  FactValue,
  IssueSeverity,
  LoreRule,
  LoreRuleScope,
  MetadataValue,
  NamedResolution,
  PovRegistryEntry,
  ResolutionSource,
  SceneFact,
  StoryChapter,
  StoryEntity,
  StoryEntityMention,
  StoryLocation,
  StoryLocationMention,
  StoryScene,
  TextNormalizer,
  TimelineRef,
} from './types'
